# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

什么时候用方法，什么时候用顶级函数
有些矩阵（5，5），有些（（5，5））如何记忆

#### 1. Import the numpy package under the name `np` (★☆☆)

In [190]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [191]:
print(np.__version__)

1.15.1


#### 3. Create a null vector of size 10 (★☆☆)

In [192]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [193]:
a = np.zeros(10)
print(a.size * a.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [194]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [196]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [197]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [198]:
a[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [199]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [200]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [201]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [202]:
# np.random.rand(27).reshape((3,3,3))
np.random.random((3,3,3))

array([[[0.67477332, 0.89090768, 0.3670525 ],
        [0.90177583, 0.23510447, 0.86677942],
        [0.78479042, 0.832448  , 0.88690994]],

       [[0.28146015, 0.46892299, 0.43317303],
        [0.31656029, 0.88483078, 0.01304107],
        [0.83978121, 0.84013651, 0.15307438]],

       [[0.65710382, 0.39504677, 0.70555765],
        [0.03315671, 0.57788671, 0.84661433],
        [0.98807688, 0.46488188, 0.53100374]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [203]:
a = np.random.rand(100).reshape(10,10)
print(a.min())
print(a.max())

0.013486047802645618
0.9905081498782333


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [204]:
a = np.random.rand(30)
a.mean()

0.4536602767809252

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [205]:
a = np.ones(15).reshape(3,5)
print(a)
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [206]:
np.pad(a,1, 'edge')

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

np.nan
Xtrue->FALSE
false
nan
true
false

In [207]:
0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

nan

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [208]:
# np.diag([0,1,2,3,4])
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [209]:
# a = np.zeros(64)
# a[::2] = 1
# a.reshape(8,8)
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [210]:
# a = np.random.rand(6*7*8).reshape(6, 7, 8)
# np.unravel_index(100,a)
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [211]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [212]:
a = np.random.random((5,5))
print((a - a.mean())/a.std())

[[ 1.16018553  1.76225692 -0.62765905  1.13431183 -0.08349717]
 [-1.47004808 -0.15819625  0.68320478 -1.2863926   0.94465241]
 [ 1.56804242 -1.17589783  1.08070707 -1.35699595 -0.82577511]
 [-0.25838044  0.68166039  0.48486029  0.6679108  -1.15650656]
 [ 0.81789234 -1.05117321 -1.27842769  0.13305746 -0.3897923 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [213]:
color = np.dtype([('r',np.ubyte, 1),
                 ('g',np.ubyte,1),
                 ('b',np.ubyte,1),
                 ('a',np.ubyte,1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [214]:
a = np.random.random((5,3))
b = np.random.random((3,2))
np.dot(a,b)

array([[1.96208532, 1.528712  ],
       [1.40291132, 1.30350231],
       [1.70252604, 1.25648457],
       [1.3700775 , 0.9941257 ],
       [1.42617951, 0.93136203]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [215]:
a = np.arange(10)
print(a)
a[(3<=a) & (a<=8)]*=(-1)
print(a)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [218]:
# print(sum(range(5),-1))

# print(np.sum(range(5),-1))

TypeError: 'numpy.ndarray' object is not callable

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
a = np.random.uniform(-10,+10,10)
print(a)
print(np.copysign(np.ceil(np.abs(a)), a))

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
np.intersect1d(a,b)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
with np.errstate(all='ignore'):
    np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1)
np.emath.sqrt(-1)
np.sqrt(-1) == np.emath.sqrt(-1)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
print(np.datetime64('today','D') - np.timedelta64(1, 'D'))
print(np.datetime64('today','D'))
print(np.datetime64('today','D') + np.timedelta64(1, 'D'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
a = np.ones(3)
b = np.ones(3) * 2
print(a,b) 
np.add(a,b,out=b)
print(a,b) 
np.divide(a,2,out=a)
print(a,b) 
np.negative(a,out=a)
print(a,b) 
np.multiply(a,b,out=a)
print(a,b) 

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [ ]:
a = np.random.uniform(0,10,10)
print(a)
print(np.floor(a))
print(np.ceil(a)-1)
print(a-a%1)
print(a.astype(int))
print(np.trunc(a))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
np.zeros((5,5)) + np.arange(5)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def func():
    for i in range(10):
        yield i
        
np.fromiter(func(), dtype=float)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.linspace(0,1,10,endpoint=False)[1:]

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
a = np.random.random(10)
a.sort()
a

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
np.add.reduce(np.arange(10))

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
a = np.random.random(10)
b = np.random.random(10)
# print(np.equal(a, b))
print(np.array_equal(a,b))
print(np.allclose(a, b))

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
a = np.random.random(10)
a.flags.writeable = False
a[1]=1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
a = np.random.random((10, 2))
x, y = a[:,0], a[:,1]
print(x, y)
print(np.sqrt(x**2 + y**2))
print(np.arctan2(y, x))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
a = np.random.random(10)
a[a.argmax()] = 0
a

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [ ]:
a = np.zeros((5, 5), [('x',float), ('y',float)])
print(a)
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(a)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
x = np.arange(10)
y = x + 0.5
c = 1.0/np.subtract.outer(x,y)
np.linalg.det(c)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min, np.finfo(dtype).max, np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
a = np.zeros((20,20))
print(a)
np.set_printoptions(threshold=np.nan)
print(a)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
a = np.arange(100)
b = np.random.uniform(0,100)
i = (np.abs(a-b)).argmin()
a[i]

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
a = np.zeros(10, [('position', [('x',float, 1), ('y', float, 1)]),
                 ('color', [('r',float,1),('g',float,1),('b',float,1)])])
a

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
a = np.random.random((100, 2))
x, y = np.atleast_2d(a[:,0], a[:, 1])
print(x, y)
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)
d

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
a = np.arange(10, dtype=np.float32)
print(a)
a = a.astype(np.int32)
print(a)

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
    6,  ,  , 7, 8\n
    ,  , 9,10,11\n""")
np.genfromtxt(s, delimiter=',', dtype=np.int)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
a = np.random.random((5,5))
for i, v in np.ndenumerate(a):
    print(i, v)
for i in np.ndindex(a.shape):
    print(i, a[i])

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d-mu)**2 / (2.0*sigma**2)))
print(g)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
a = np.zeros((n, n))
np.put(a, np.random.choice(range(n*n), p, replace=False), 1)
a

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
a = np.random.random((10,10))
means = a.mean(axis=1)
a - means

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
a = np.random.random((3,3))
print(a)
print(a[:,1].argsort())
print(a[a[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
a = np.random.randint(0,3,(3,10))
print(a.any(axis=0))
print(~a.any(axis=0))
print((~a.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
a = np.random.random((3,3))
i = np.random.uniform(0,1)
print('a:',a,'i:',i)
a.flat[np.abs(a-i).argmin()]

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x, y, z in it:
    z[...] = x + y
    
print(it.operands[2])    

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NameArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

a = NameArray(np.arange(10), "range_10")
a.name

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
a = np.ones(10)
i = np.random.randint(0,len(a),20)
print(a, i)
np.add.at(a, i, 1)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
a = np.random.randint(0,5,5)
i = np.arange(5)
print(a, i)
np.bincount(a, i)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [ ]:
w,h = 16,16
i = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f = i[...,0]*(256*256) + i[...,1]*256 +i[...,2]
len(np.unique(f))

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
a = np.random.randint(0,10,(4,3,4))
print(a)
a.sum(axis=(-2,-1))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print(D, S)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
a = np.random.random((5,5))
b = np.random.random((5,5))
np.diag(np.dot(a,b))

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
a = np.array([1,2,3,4,5])
n = 3
Z0 = np.zeros(len(a) + (len(a)-1)*(n))
Z0[::n+1] = a
print(Z0)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
a = np.random.random((3,3))
print(a)
a[[0,1]] = a[[1,0]]
print(a)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
c = np.bincount([1,1,2,3,4,4,6])
np.repeat(np.arange(len(c)), c)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

a = np.arange(20)
moving_average(a, n=3)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
a = np.random.randint(0,2,100)
np.logical_not(a, out=a)
b = np.random.uniform(-1.0,1.0,100)
np.negative(b, out=b)
print(a,b)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
np.array([distance(P0,P1,p_i) for p_i in p])

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [ ]:
a = np.arange(1,15,dtype=np.uint32)
stride_tricks.as_strided(Z,(11,4),(4,4))

#### 82. Compute a matrix rank (★★★)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
print(U, S, V)
rank = np.sum(S > 1e-10)
print(rank)

#### 83. How to find the most frequent value in an array?

In [ ]:
a = np.random.randint(0,10,50)
print(a)
np.bincount(a).argmax()

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
print(S)
S[2,3] = 42
print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
np.tensordot(M, V, axes=[[0, 2], [0, 1]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
a = np.ones((16,16))
k = 4
np.add.reduceat(np.add.reduceat(a,np.arange(0, a.shape[0], k), axis=0),
                                np.arange(0, a.shape[1], k), axis=1)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
a = np.arange(10)
np.random.shuffle(a)
print(a)
n=5
print(np.argsort(a)[-n:])
print(a[np.argsort(a)[-n:]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
a = np.random.random(1000)
np.power(x,3)
x*x*x
np.einsum('i,i,i->i',x,x,x)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))
c = (a[..., np.newaxis, np.newaxis] == b)
print(c)
np.where(c.any((3,1)).all(1))[0]

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
a = np.random.randint(0,5,(10,3))
E = np.all(a[:,1:] == a[:,:-1], axis=1)
print(E)
U = a[~E]
print(U)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
i = np.random.randint(0,10,10)
b = ((i.reshape(-1,1)&(2**np.arange(8)))!=0).astype(int)
print(b)
print(b[:,::-1])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
print(T)
_, idx = np.unique(T, return_index=True)
print(idx)
uZ = Z[idx]
print(uZ)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
a = np.random.uniform(0,1,10)
b = np.random.uniform(0,1,10)

np.einsum('i->', a)
np.einsum('i,i->i', a, b)
np.einsum('i,i', a, b)
np.einsum('i,j->ij', a, b)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
# print(x, y)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)
# print(r_int, x_int, y_int)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
x = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(x, 1) == 0, axis=-1)
print(M)
M &= (x.sum(axis=-1) == n)
print(x[M])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
a = np.random.randn(100)
n = 1000
i = np.random.randint(0, a.size, (n, a.size))
means = a[i].mean(axis=1)
np.percentile(means, [2.5, 97.5])